default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: deploy_app_development
  host: <%= ENV['DATABASE_HOST'] || Rails.application.credentials.database.db_host %>
  username: <%= ENV['DATABASE_USERNAME'] || Rails.application.credentials.database.db_user %>
  password: <%= ENV['DATABASE_PASSWORD'] || Rails.application.credentials.database.db_password %>

test:
  <<: *default
  database: deploy_app_test
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: deploy_app_production
  username: deploy_app
  password: <%= ENV["DEPLOY_APP_DATABASE_PASSWORD"] %>
